import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { RegistraCopiaLocale } from "@/components/CopiaLocale";
import { Intestazione } from "@/components/Intestazione";
import { PieDiPagina } from "@/components/PieDiPagina";
import { colori } from "@/config/tokens";
import { m } from "@/lib/messaggi";
import { inclusiveSans } from "./font";
import "./globals.css";

/**
 * The icons are declared here and generated by strumenti/genera-icone.mjs;
 * the rest of what the phone needs to install the app is in app/manifest.ts,
 * which Next links from every page on its own (§12 step 13).
 *
 * iPhone ignores the manifest's icons and takes `apple` alone — and, being
 * the browser that never offers the installation, it is also the one whose
 * icon is most likely to be missing if nobody declares it.
 */
export const metadata: Metadata = {
  title: m.app.nome,
  icons: {
    icon: "/icona-192.png",
    apple: "/icona-apple-180.png",
  },
  appleWebApp: { capable: true, title: m.app.nomeBreve, statusBarStyle: "default" },
};

/**
 * The colour the phone paints its own frame with, around the installed app.
 * `sfondo` is what the header already sits on (§13.8), so the cream ground
 * reaches the edge of the screen instead of opening inside a white border.
 */
export const viewport: Viewport = { themeColor: colori.sfondo };

// Root layout — SPEC §13.8: header and footer carry the continuity with the
// institutional site; pages render inside a single text column.
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="it" className={inclusiveSans.variable}>
      <body className="flex min-h-dvh flex-col">
        <RegistraCopiaLocale />
        <Intestazione />
        <main className="mx-auto w-full max-w-contenuto flex-1 px-4 py-10">{children}</main>
        <PieDiPagina />
      </body>
    </html>
  );
}
